_schema-version: '3.1'
ID: ProjectONE
version: 1.0.0
description: A simple CAP project.
parameters:
  deploy_mode: html5-repo
  enable-parallel-deployments: true
  subdomain: ff21e6eftrial
build-parameters:
  before-all:
    - builder: custom
      commands:
        - rm -rf build/dist
        - mkdir -p build/dist
        - rm -rf build/ui-deployer
        - mkdir -p build/ui-deployer
    - builder: custom
      commands:
        - npm install --production
        - >-
          bash -c "cds -v | grep 'cds-dk' || npm i --production --no-save
          @sap/cds-dk"
        - bash -c "export PATH=$PATH:$(pwd)/node_modules/.bin"
        - cds build --production
  after-all:
    - builder: custom
      commands:
        - npm install
modules:
  - name: ProjectONE-riskmitigation.ui5
    type: html5
    path: app/ui5
    build-parameters:
      builder: custom
      commands:
        - rm -rf dist-zip dist
        - npm install
        - >-
          npx -p @ui5/cli@^3.0.0 ui5 build --dest dist
          --include-task=generateCachebusterInfo
        - mkdir dist-zip
        - bash -c "cd dist && npx bestzip ../dist-zip/riskmitigationui5.zip *"
      _artifactName: riskmitigationui5.zip
      supported-platforms: []
      build-result: dist-zip
  - name: ProjectONE-db-deployer
    type: hdb
    path: gen/db
    parameters:
      buildpack: nodejs_buildpack
    build-parameters:
      builder: npm
      ignore:
        - node_modules
        - package-lock.json
    requires:
      - name: ProjectONE-service-uaa
      - name: ProjectONE-service-db
  - name: ProjectONE-srv
    type: nodejs
    path: gen/srv
    parameters:
      memory: 256MB
    provides:
      - name: srv-api
        properties:
          srv-url: ${default-url}
    build-parameters:
      builder: npm
      ignore:
        - node_modules
        - package-lock.json
    requires:
      - name: ProjectONE-service-uaa
      - name: ProjectONE-service-db
      - name: ProjectONE-service-destination
      - name: ProjectONE-service-metadata
      - name: ProjectONE-service-connectivity
      - name: ProjectONE-service-logs
  - name: ProjectONE-aux-destinations
    type: com.sap.application.content
    parameters:
      content:
        subaccount:
          existing_destinations_policy: update
          destinations:
            - Authentication: OAuth2UserTokenExchange
              Name: ProjectONE-service-uaa
              ServiceInstanceName: ProjectONE-uaa
              ServiceKeyName: ProjectONE-uaa-key
              sap.cloud.service: lcap.ProjectONE
            - Authentication: OAuth2UserTokenExchange
              Name: ProjectONE-app-srv
              TokenServiceInstanceName: ProjectONE-uaa
              TokenServiceKeyName: ProjectONE-uaa-key
              URL: ~{srv-api/srv-url}
              sap.cloud.service: lcap.ProjectONE
            - Name: ProjectONE-service-html5-apps-repo-host
              ServiceInstanceName: ProjectONE-html5-apps-repo-host
              ServiceKeyName: ProjectONE-html5-apps-repo-host-key
              sap.cloud.service: lcap.ProjectONE
            - Authentication: OAuth2UserTokenExchange
              Name: ProjectONE-ProjectONEService
              TokenServiceInstanceName: ProjectONE-uaa
              TokenServiceKeyName: ProjectONE-uaa-key
              URL: ~{srv-api/srv-url}/service/ProjectONEService
              sap.cloud.service: lcap.ProjectONE
              sap.applicationdevelopment.actions.enabled: false
              sap.build.usage: CAP
              sap.processautomation.enabled: false
              HTML5.DynamicDestination: false
              WebIDEEnabled: false
              MobileEnabled: false
              AppgyverEnabled: false
    build-parameters:
      no-source: true
    requires:
      - name: ProjectONE-service-uaa
        parameters:
          service-key:
            name: ProjectONE-uaa-key
      - name: srv-api
      - name: ProjectONE-service-html5-apps-repo-host
        parameters:
          service-key:
            name: ProjectONE-html5-apps-repo-host-key
      - name: ProjectONE-service-destination
        parameters:
          content-target: true
  - name: ProjectONE-launchpad
    type: html5
    path: build/launchpad
    build-parameters:
      builder: custom
      commands:
        - npm install
        - >-
          npx -p @ui5/cli@^3.0.0 ui5 build --dest dist
          --include-task=generateCachebusterInfo
        - bash -c "cd dist && npx bestzip ../../../build/dist/launchpad.zip *"
        - rm -rf dist
      _artifactName: launchpad.zip
      supported-platforms: []
      build-result: ../../build/dist
  - name: ProjectONE-aux-ui-deployer
    type: com.sap.application.content
    path: build/ui-deployer
    build-parameters:
      build-result: resources
      requires:
        - name: ProjectONE-riskmitigation.ui5
          artifacts:
            - riskmitigationui5.zip
          target-path: resources
        - name: ProjectONE-launchpad
          artifacts:
            - launchpad.zip
          target-path: resources
    requires:
      - name: ProjectONE-service-html5-apps-repo-host
        parameters:
          content-target: true
resources:
  - type: org.cloudfoundry.managed-service
    name: ProjectONE-service-uaa
    parameters:
      service: xsuaa
      service-plan: application
      service-name: ProjectONE-uaa
      path: xs-security.json
      config:
        oauth2-configuration:
          redirect-uris:
            - https://${subdomain}.launchpad.${default-domain}/login/*
            - https://${subdomain}.${default-domain}/login/*
          credential-types:
            - binding-secret
            - x509
        xsappname: ProjectONE-${space}
        role-collections:
          - description: RiskViewer
            name: ProjectONE-RiskViewer-${space}
            role-template-references:
              - $XSAPPNAME.RiskViewer
          - description: RiskManager
            name: ProjectONE-RiskManager-${space}
            role-template-references:
              - $XSAPPNAME.RiskManager
  - type: org.cloudfoundry.managed-service
    name: ProjectONE-service-db
    parameters:
      service: hana
      service-plan: hdi-shared
      service-name: ProjectONE-db
  - type: org.cloudfoundry.managed-service
    name: ProjectONE-service-destination
    parameters:
      service: destination
      service-plan: lite
      service-name: ProjectONE-destination
      config:
        HTML5Runtime_enabled: true
        version: 1.0.0
  - type: org.cloudfoundry.user-provided-service
    name: ProjectONE-service-metadata
    parameters:
      service: metadata
      service-plan: standard
      service-name: ProjectONE-metadata
      config:
        default-domain: ${default-domain}
  - type: org.cloudfoundry.managed-service
    name: ProjectONE-service-connectivity
    parameters:
      service: connectivity
      service-plan: lite
      service-name: ProjectONE-connectivity
  - type: org.cloudfoundry.managed-service
    name: ProjectONE-service-logs
    parameters:
      service: application-logs
      service-plan: lite
      service-name: ProjectONE-logs
  - type: org.cloudfoundry.managed-service
    name: ProjectONE-service-html5-apps-repo-host
    parameters:
      service: html5-apps-repo
      service-plan: app-host
      service-name: ProjectONE-html5-apps-repo-host
